### ISSUE TITLE
Speakers for Open Gov & Civic Tech Meetups in 2017

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/iced-coffee#201] opened 2016-11-29 03:50 UTC
- [x] JAN 23: short update from Fellowship Permitting Team, B-Cycle Data - [Tim Gasser](https://github.com/timgasser/bcycle-austin/issues/1)
- [x] FEB 27: CoA Fellows Presentation, ATX Floods
- [x] MAR 20: short update from Austin Election Finance, Kathryn Darnall
- [x] APR 17: short update from David E with ATA
- [x] MAY 15: 
- [x] JUNE 19: Jess Sauer - Keep My Casa (2017 ATX Hack for Change project) & Stephanie Trinh - housing/tenants rights activist and Attorney at Texas RioGrande Legal Aid 
- [x] JULY 17: Tara Vancil and Paul Frazee, [Beaker Browser](https://beakerbrowser.com/)
- [x] AUG 21: Lightning Talks
- [x] SEPT 18: Speaker// Amy Stansbury +  COA
- [x] OCT 16: Redistricting+ Gerrymandering
- [x] NOV 20: Feedback night
- [x] DEC 18: Open Government in Austin// ATA + COA + Ourselves & a community workshop

_here is what we did last year #46_ 

Ideas:
- Journalists from community impact, statesman, or tribune working on data apps
  - Cindy Royal from Texas State and Hack and Hackers
  - "Hey how'd you get that!?" Journalists share secrets to a successful FOIA request (could be the same talk as Cindy Royal?)
- Andy Thorton on d3: http://encodingpixels.com/
- Jon Lebkowsky from EFF Austin
- http://sevenmilemedia.com/work/
- Armand Chaput from UT about applications for drones by City agencies. http://www.austinmonitor.com/stories/2016/04/austin-fire-department-soon-using-drones/ 
- **[reached out & pending]** CryptoParty workshop with EFF like Chi Hack Night [link](https://github.com/chihacknight/breakout-groups/issues/59#issuecomment-263470005)
- **[reached out & interested]** Jon Lyons from data.world to talk about collaboration on their hate crimes dataset
- Kelley Shannon, Freedom of Information Foundation of Texas, http://foift.org/contact/
- UT EPA Water Infrastructure Center - http://twri.tamu.edu/publications/conservation-matters/2016/november/ut-austin-engineering-becomes-new-home-for-epa-water-infrastructure-center/
- Hayley Hughes- IBM data design. Andy can get us a connection to her we just need a topic.
- [Andrew Blumberg](https://www.ma.utexas.edu/users/blumberg/) is a UT math professor organizing a [workshop next February about the geometry of redistricting](https://sites.tufts.edu/gerrymandr/). The sponsoring organization says: "We believe that gerrymandering of all kinds is a fundamental threat to our democracy." Separately, he worked with EFF on [GPS location data privacy](https://www.ma.utexas.edu/users/blumberg/locational_privacy.html).
- Four people from the Texas Department of Information Resources are leading events at SXSW 2018. We could ask if they want to preview their talks for us. [Ed Kelly and Ingrid Olsson](https://schedule.sxsw.com/2018/events/PP73049), [Ean Meacham](https://schedule.sxsw.com/2018/events/PP72779), [Hannah-Kate Schaeffer](https://schedule.sxsw.com/2018/events/PP72739) (the last one is a meetup, not a presentation).

**Comment by werdnanoslen** [comment] 2017-09-05 00:09
a couple suggestions based on our survey a while ago (https://github.com/open-austin/iced-coffee/issues/241#issuecomment-327040775):

- Something on data storage/vis using Socrata, CartoDB, ArcGIS, and others, possibly with another meetup group with the skills that our members need (programming, data analysis and cleaning)
- Project management/process workshop, again possibly with another meetup group with PM skills so that we can create a long-term relationship

**Comment by VictoriaODell** [comment] 2017-09-07 23:37
Compiling suggested speakers from the #iced-coffee slack channel here: 

MapD

> Thank you very much for your prompt response. 
> 
> We would value the opportunity to present at a Meetup for Open Austin. 
> 
> Here is the abstract below. If you share some dates, I can confirm on the calendar and we can lock something down right away and get to the production element to ensure success. October, November, and Mid-December could be good. Please let me know what works for you. 
> 
> Oh, also, my buddy, Mark Collier (co-founder of OpenStack) is interested in knowing your team, as he also lives in Austin. :) Happy to make an intro. Please let me know if you’re interested. 
> 
> 
> Thank you! 
> 
> ##
> 
> Using GPUs for Lightning Fast Analytics on MapD
> 
> GPU-powered in-memory databases and analytics platforms are the logical successor to CPU in-memory systems, largely due to recent increases in the onboard memory available on GPUs. With sufficient memory, GPUs possess numerous advantages over CPUs, including much greater compute and memory bandwidth, as well as a native graphics pipeline for visualization.
> 
> In this talk, we will demo how MapD is able to leverage multiple GPUs per server to extract orders-of-magnitude performance increases over CPU-based systems, bringing interactive querying and visualization to multi-billion (with a ‘b’) row datasets.
> 
> Thanks!
> 
> All the best,
> 
> Patricia

idea From @mscarey 
> Another library speaker idea is Andrew Blumberg (https://www.ma.utexas.edu/users/blumberg/), a UT math professor organizing a workshop next February about the geometry of redistricting (https://sites.tufts.edu/gerrymandr/). The sponsoring organization says: "We believe that gerrymandering of all kinds is a fundamental threat to our democracy." Separately, he worked with EFF on GPS location data privacy (https://www.ma.utexas.edu/users/blumberg/locational_privacy.html).

idea from @mscarey 
> Also, the city's Office of Sustainability has a "Request a Speaker" page. https://www.austintexas.gov/page/learning-about-sustainability


Idea from @mateoclarke 
> One idea is to invite Taylor Barnett, she’s Austin based and has been doing volunteer work via Sketch City for Harvey/Irma
> https://twitter.com/taylor_atx/status/905631331073179648
> Taylor Barnett @taylor_atx
> I have a lot of feels about all the tech work that's being done around these hurricanes. I'll save them for later. *Now* we need volunteers:


City of Austin 
> Emailed 
>"if you just have time for us to talk about open jobs, 5-10 mins is fine. But if you don't have a speaker, we can maybe find someone to give a talk about a current project."
>
> "def let us know if you need a speaker – we’re thinking of announcing a recruiting push for the fellows program on the 18th so the timing could work well; could even invite press to come by."

**Comment by VictoriaODell** [comment] 2017-09-08 00:00
Also adding that my coworker at Anaconda mentioned being able to speak about Gerrymandering and redistricting. I believe he has a project that he is working on around it and has a presentation he is doing later this month. GlassHouse policy also has interest in the topic and has worked on an app for a game night. 

I would say Having a speaker or multiple speakers come out to talk about this is important.

**Comment by VictoriaODell** [comment] 2017-09-11 17:48
Spoke with Amy to get Monday finalized. Current Run of show for Monday looks like this: 

Here is our current setup: 
6:45pm Doors open
7:00pm Programming with announcements + Intros
7:10pm Open Austin Updates
7:20 City of Austin slot for fellowship + Q&A (15 minutes)
7:35-8:30pm Amy Stansbury does Civics 101 + Q&A


Confirming the fellowship time slot with the city. 

Amy will be covering basics for getting engaged and involved with our city and be showing resources available and opportunities to plug in.

**Comment by VictoriaODell** [comment] 2017-09-11 17:49
That was fast, city confirmed. Updating our September event page. We can start planning October next.

**Comment by werdnanoslen** [comment] 2017-09-16 21:23
As part of a way to entice folks from Data for Democracy to join, perhaps we invite Jon Lyons to talk about the hate crimes dataset for the October 16 meetup? Who knows Jon?

**Comment by VictoriaODell** [comment] 2017-09-17 16:55
@werdnanoslen who is Jon Lyons? I looked through our meetup messages and it seems like someone from New Knowledge, the company behind D4D, messaged us about doing events together. I just sent a follow-up saying a few of us planned on going to their 30th meetup. 

And what is the "Hate crimes dataset"? I'm interested. I have a strong interest in getting redistricting at our October or November meetup. This is a super important issue around mapping, data, and policy. Glasshouse Policy is working on a gerrymandering/redistricting app right now too. I saw a prototype recently. They said they needed some help to getting to done though.

**Comment by werdnanoslen** [comment] 2017-09-17 18:10
I dunno, he's listed in the first post here

**Comment by VictoriaODell** [comment] 2017-09-20 05:14
I'll check in with the following people for October: 
- My Co-worker at Anaconda,  Micheal Sarahan. He recently gave a presentation on redistricting
- Glasshouse policy, they are working on another game night and application that needs some help
- Maybe one other? I'll check in with those people and see their availability and thoughts.

**Comment by VictoriaODell** [comment] 2017-09-27 18:53
Here is a video and the slides from my coworker: 
https://www.youtube.com/watch?v=SJzCgC4eguw&feature=youtu.be

I sent him info and am checking to see what he's thinking/needs. Would still like to reach out to Glasshouse and get them to mention their game night/ app.

**Comment by werdnanoslen** [comment] 2017-10-18 22:34
For the 20th we might re-invite Hayley Hughes to talk about data and also to recap their Design Week event?

**Comment by VictoriaODell** [comment] 2017-10-19 06:16
Hey @werdnanoslen I'd like us to host something that is focused on getting community feedback for next year. Thoughts on that? Also, thinking we should make some upcoming hack nights a time for feedback.

**Comment by werdnanoslen** [comment] 2017-10-19 19:43
Yeah, I'm down, but Isn't that what the Dec 18 meetup is for?

**Comment by VictoriaODell** [comment] 2017-10-19 20:02
I'm envisioning it in 2 parts. Feedback needed. 

1) Nov: Review where we are at/ have done. Ask community for feedback, input, ideas + invite our partners and other leaders.
   
2)  Dec: Come back with some synthesized actions for how we will move forward in 2018. 

And also using November and December hack events to source community ideas and feedback more intentionally.

**Comment by werdnanoslen** [comment] 2017-10-19 20:25
I like it! Haven't done something quite like that before in this context,
but maybe we can make a workshop out of it? I'll make an outline of what
I'm thinking of and post tonight...

**Comment by VictoriaODell** [comment] 2017-11-29 23:17
Wee! All planned for this year. Closing this out. 

Before I close, I want to bubble up this comment I made from the previous year's planning thread. In 2018 I think library meetings can have some more discussion time like mentioned below. Especially so based on the feedback we got from our latest community session. 

> 
> I think we should also consider short discussions followed by break-out groups. 
> 
> I've done that previously within an organization(Feminists United) and it got a great response since everyone got presented to for a bit and then we went into smaller groups to further discuss the issues. In the end we came together and recapped a bit on what each group discussed in relation to the topic. 
> 
> We did this for issues such as racism, classism, privlege, etc. It helped people stay engaged and made us a tighter community. 
> 
> We did a few things in that group that I really liked and need to probably share. 
> 1. We quickly addressed 3 headlines that were related to our cause at the beginning of the session. It was always better if they corresponded with the topic but sometimes it was more about current events. 
> 1. We switched it up between breakout groups/ presentations hosted by core team members, curated guest panels, and presentations by outside individuals(We had PPTXV come talk about voting rights, etc ). Also though, these meetings were held weekly so we had a lot more topics to cover and ultimately planning to do. I was on a team of about 7 people.
> 2. At the end of the meeting, we had anonymous paper feedback cards that asked what each person liked/ thinks needs adjustments. This helped us gauge how each meeting went and helped us in planning future meetings. 
> 3. As a feminist group, we were very particular about the use of personal pronouns in intros. I'd like to see that in more spaces but would like to know what the group thinks. Being more cognizant of things like really shows respect for underrepresented and underserved communities. I've heard that the Sass group does that too. It's a really small thing that can make a big difference for people. 
> 
> I learned a lot with that group and in a semster we grew 3x our orignial size because of better marketing(new logos, social media curation/maintenance,etc ), meeting structure, and overall organization. Let me know what ya'll think about the above and if we can incoporate any of it moving forward. 
> 
> Let me know if y'all have any questions too. I can maybe dig around and find some old stuff that we used. I think that group took a lot more work since we met weekly but  there were 7 people on the team.
>

**Closed by VictoriaODell** 2017-11-29 23:17 UTC
Labels: events, in progress
